services:
  - type: web
    name: webtech25-backend
    runtime: docker               # <— wichtig: KEIN env: java mehr
    plan: free                    # oder starter/pro – je nach Tarif

    # Build-Argumente aus Dockerfile (optional, falls benötigt)
    buildArgs:
      DATABASE_password: ${DATABASE_password}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_username: ${DATABASE_username}

    envVars:                      # Laufzeit-Variablen
      - key: SPRING_PROFILES_ACTIVE
        value: production