services:
  - type: web
    name: Webtech25
    env: java
    buildCommand: |
      chmod +x gradlew
      ./gradlew build
    startCommand: ./gradlew bootRun
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
